export const SET_AUTH_USER = 'SET_AUTH_USER'
export const GET_GROUPS = 'GET_GROUPS'
export const SET_ERRORS = 'SET_ERRORS'
export const GET_USER = 'GET_USER'
export const SET_COURSES = 'SET_COURSES'
export const GET_PARTICIPATIONS = 'GET_PARTICIPATIONS'
