# Generated by Django 3.1.1 on 2021-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210125_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='categories',
            field=models.ManyToManyField(blank=True, to='todos.Category'),
        ),
    ]
