# Generated by Django 3.1.1 on 2021-04-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion date')),
                ('is_complete', models.BooleanField(verbose_name='Is complete')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField(verbose_name='Position number')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.course')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_courses.task_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.task')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courses.task',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.task')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courses.task',),
        ),
        migrations.CreateModel(
            name='ReadingMaterialProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseprogress')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_time', models.DateTimeField(verbose_name='Enroll date')),
                ('role', models.CharField(choices=[('TH', 'Teacher'), ('ST', 'Student')], default='ST', max_length=2, verbose_name='Role')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.participation'),
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(through='courses.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('is_right', models.BooleanField(verbose_name='Is right')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question')),
            ],
        ),
        migrations.CreateModel(
            name='TestProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseprogress')),
                ('reading_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.readingmaterial')),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('course', 'position_number'), name='positioning'),
        ),
        migrations.AddField(
            model_name='readingmaterialprogress',
            name='reading_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.readingmaterial'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.test'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('course_id', 'user'), name='participation_constraint'),
        ),
    ]
