# Generated by Django 3.1.1 on 2021-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position_number',
            field=models.IntegerField(verbose_name='Position number'),
        ),
    ]
