# Generated by Django 3.1.1 on 2021-04-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participation',
            name='participation_constraint',
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='participation_constraint'),
        ),
    ]
