# Generated by Django 3.1.1 on 2021-04-06 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210406_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='enroll_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 6, 23, 55, 0, 177269), verbose_name='Enroll date'),
        ),
    ]
