# Generated by Django 3.1.1 on 2021-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210406_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='enroll_time',
            field=models.DateTimeField(verbose_name='Enroll date'),
        ),
    ]
