# Generated by Django 3.1.1 on 2021-04-06 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210407_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='enroll_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 0, 8, 38, 73602), verbose_name='Enroll date'),
        ),
    ]
