# Generated by Django 3.1.1 on 2021-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210407_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='enroll_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enroll date'),
        ),
    ]
