# Generated by Django 3.1.1 on 2021-04-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210407_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseprogress')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.task')),
            ],
        ),
        migrations.RemoveField(
            model_name='testprogress',
            name='course_progress',
        ),
        migrations.RemoveField(
            model_name='testprogress',
            name='reading_material',
        ),
        migrations.DeleteModel(
            name='ReadingMaterialProgress',
        ),
        migrations.DeleteModel(
            name='TestProgress',
        ),
    ]
