# Generated by Django 3.1.1 on 2021-04-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210408_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.participation', unique=True),
        ),
    ]
