# Generated by Django 3.1.1 on 2021-04-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210411_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='participation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.participation'),
        ),
    ]
