# Generated by Django 3.1.1 on 2021-04-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210411_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='is_complete',
        ),
    ]
