# Generated by Django 3.1.1 on 2021-04-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210412_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is complete'),
        ),
    ]
