# Generated by Django 3.1.1 on 2021-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_courseprogress_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterialprogress',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is complete'),
        ),
        migrations.AlterField(
            model_name='testprogress',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is complete'),
        ),
    ]
