# Generated by Django 3.1.1 on 2021-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210415_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is done'),
        ),
    ]
